name: Build CI

on: push

jobs:
  build-linux:
    name: Build - Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1.13
        with:
          rustflags: ""
      - name: Build binary
        run: cargo build --release
      - uses: actions/upload-artifact@v4
        with:
          name: robostart-linux
          path: target/release/robostart
  build-host:
    strategy:
      matrix:
        include:
          - os: windows
            runner: windows-latest
            suffix: ".exe"
          - os: macos
            runner: macos-latest
            suffix: ""
    name: "Build - ${{ matrix.os }}"
    runs-on: "${{ matrix.runner }}"
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1.13
        with:
          rustflags: ""
      - name: Build binary
        run: cargo build --release
      - uses: actions/upload-artifact@v4
        with:
          name: "robostart-${{ matrix.os }}"
          path: "target/release/robostart/${{ matrix.suffix }}"